# Generated by Django 3.2 on 2021-05-01 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0006_comments_section_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments_section',
            old_name='username',
            new_name='User',
        ),
    ]
