# Generated by Django 3.2 on 2021-05-02 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0014_editprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EditProfile',
        ),
    ]
