# Generated by Django 3.2 on 2021-05-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0018_auto_20210510_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='Technical', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.TextField(default='this is a snippet for the blog'),
        ),
    ]
