# Generated by Django 3.2 on 2021-05-30 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0019_auto_20210512_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='snippet',
            field=models.TextField(),
        ),
    ]
