# Generated by Django 3.2 on 2021-06-17 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0022_alter_contactus_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contactus',
        ),
    ]
